
alias screen='screen -h 5000'
alias ls='ls -p'
alias :G='git'
alias :B='boson'
alias :C='cheat'
alias :T='thor'
alias :TT='thor -T'
alias :H='heroku'
alias rd='rdebug --no-stop'
alias ss='rake log:clear; ./script/server -u'
alias lt='RBENV_VERSION=ree-1.8.7-2012.02 lifetracker'
alias dbsh32='RBENV_VERSION=ree-1.8.7-2012.02-32bit NLS_LANG=AMERICAN.US7ASCII DYLD_LIBRARY_PATH=~/Applications/instantclient_10_2_32bit TNS_ADMIN=~/.sqlplus dbsh'
alias tmuxnew='tmux new-session -s $(basename $(pwd))'
